export const ErrorCodeEnum = {
  ACCESS_UNAUTHORIZED: 'ACCESS_UNAUTHORIZED',
  ACCESS_FORBIDDEN: 'ACCESS_FORBIDDEN',

  AUTH_USER_NOT_FOUND: 'AUTH_USER_NOT_FOUND',

  AUTH_EMAIL_ALREADY_EXISTS: 'AUTH_EMAIL_ALREADY_EXISTS',
  AUTH_INVALID_TOKEN: 'AUTH_INVALID_TOKEN',

  AUTH_EMAIL_PENDING_VERIFICATION: 'AUTH_EMAIL_PENDING_VERIFICATION',
  AUTH_OTP_EXPIRED: 'AUTH_OTP_EXPIRED',
  AUTH_OTP_INVALID: 'AUTH_OTP_INVALID',
  AUTH_OTP_TOO_MANY_REQUESTS: 'AUTH_OTP_TOO_MANY_REQUESTS',

  AUTH_NOT_FOUND: 'AUTH_NOT_FOUND',
  AUTH_TOO_MANY_ATTEMPTS: 'AUTH_TOO_MANY_ATTEMPTS',
  AUTH_UNAUTHORIZED_ACCESS: 'AUTH_UNAUTHORIZED_ACCESS',
  AUTH_TOKEN_NOT_FOUND: 'AUTH_TOKEN_NOT_FOUND',
  AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  AUTH_PASSWORD_MUST_BE_DIFFERENT: 'AUTH_PASSWORD_MUST_BE_DIFFERENT',

  // Validation and Resource Errors
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  FILE_UPLOAD_ERROR: 'FILE_UPLOAD_ERROR',

  // Request Errors
  REQUEST_TIMEOUT: 'REQUEST_TIMEOUT',
  REQUEST_TOO_LARGE: 'REQUEST_TOO_LARGE',
  UNSUPPORTED_MEDIA_TYPE: 'UNSUPPORTED_MEDIA_TYPE',

  // System Errors
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR'
} as const

export type ErrorCodeEnumType = keyof typeof ErrorCodeEnum
