import { getEnv } from '../utils/get-env.util'

const encryptionSecret: string = getEnv('ENCRYPTION_SECRET')
const jwtSecret: string = getEnv('JWT_SECRET')
const jwtRefreshSecret: string = getEnv('JWT_REFRESH_SECRET')

const envConfig = () => ({
  NODE_ENV: getEnv('NODE_ENV', 'development'),

  PORT: getEnv('PORT', '8000'),
  BASE_PATH: getEnv('BASE_PATH', '/api'),

  MONGO_URI: getEnv('MONGO_URI'),
  MONGO_MAX_POOL_SIZE: getEnv('MONGO_MAX_POOL_SIZE', '50'),
  MONGO_SERVER_SELECTION_TIMEOUT: getEnv(
    'MONGO_SERVER_SELECTION_TIMEOUT',
    '8000'
  ),
  MONGO_SOCKET_TIMEOUT: getEnv('MONGO_SOCKET_TIMEOUT', '45000'),
  MONGO_CONNECT_TIMEOUT: getEnv('MONGO_CONNECT_TIMEOUT', '10000'),
  MONGO_MAX_POOL_SIZE_PER_CORE: getEnv('MONGO_MAX_POOL_SIZE_PER_CORE', '5'),
  MEMORY_THRESHOLD_MB: getEnv('MEMORY_THRESHOLD_MB', '500'),

  JWT_SECRET: jwtSecret,
  JWT_EXPIRES_IN: getEnv('JWT_EXPIRES_IN', '15m') as string,
  JWT_ISSUER: getEnv('JWT_ISSUER', 'finsight-api'),

  JWT_REFRESH_SECRET: jwtRefreshSecret,
  JWT_REFRESH_EXPIRES_IN: getEnv('JWT_REFRESH_EXPIRES_IN', '7d') as string,
  JWT_ACCESS_CURRENT_KID: getEnv('JWT_ACCESS_CURRENT_KID', 'access-current'),
  JWT_ACCESS_CURRENT_SECRET: getEnv('JWT_ACCESS_CURRENT_SECRET', jwtSecret),
  JWT_ACCESS_PREVIOUS_KID: getEnv('JWT_ACCESS_PREVIOUS_KID', ''),
  JWT_ACCESS_PREVIOUS_SECRET: getEnv('JWT_ACCESS_PREVIOUS_SECRET', ''),
  JWT_REFRESH_CURRENT_KID: getEnv('JWT_REFRESH_CURRENT_KID', 'refresh-current'),
  JWT_REFRESH_CURRENT_SECRET: getEnv(
    'JWT_REFRESH_CURRENT_SECRET',
    jwtRefreshSecret
  ),
  JWT_REFRESH_PREVIOUS_KID: getEnv('JWT_REFRESH_PREVIOUS_KID', ''),
  JWT_REFRESH_PREVIOUS_SECRET: getEnv('JWT_REFRESH_PREVIOUS_SECRET', ''),
  JWT_ACCESS_LEGACY_FALLBACK_ENABLED: getEnv(
    'JWT_ACCESS_LEGACY_FALLBACK_ENABLED',
    'true'
  ),
  JWT_REFRESH_LEGACY_FALLBACK_ENABLED: getEnv(
    'JWT_REFRESH_LEGACY_FALLBACK_ENABLED',
    'true'
  ),
  REFRESH_TOKEN_ROTATION_GRACE_SECONDS: getEnv(
    'REFRESH_TOKEN_ROTATION_GRACE_SECONDS',
    '10'
  ),
  ENCRYPTION_SECRET: encryptionSecret,
  TOKEN_HASH_SECRET: getEnv('TOKEN_HASH_SECRET'),

  GEMINI_API_KEY: getEnv('GEMINI_API_KEY'),

  CLOUDINARY_CLOUD_NAME: getEnv('CLOUDINARY_CLOUD_NAME'),
  CLOUDINARY_API_KEY: getEnv('CLOUDINARY_API_KEY'),
  CLOUDINARY_API_SECRET: getEnv('CLOUDINARY_API_SECRET'),

  RESEND_API_KEY: getEnv('RESEND_API_KEY'),
  RESEND_MAILER_SENDER: getEnv('RESEND_MAILER_SENDER', ''),

  SENTRY_DSN: getEnv('SENTRY_DSN', ''),
  SENTRY_RELEASE: getEnv('SENTRY_RELEASE', ''),
  SENTRY_TRACES_SAMPLE_RATE: getEnv('SENTRY_TRACES_SAMPLE_RATE', '0.1'),
  SENTRY_BACKGROUND_ERRORS_ENABLED: getEnv(
    'SENTRY_BACKGROUND_ERRORS_ENABLED',
    'true'
  ),

  METRICS_ENABLED: getEnv('METRICS_ENABLED', 'true'),
  METRICS_ROUTE: getEnv('METRICS_ROUTE', '/metrics'),
  METRICS_QUEUE_POLL_INTERVAL_MS: getEnv(
    'METRICS_QUEUE_POLL_INTERVAL_MS',
    '15000'
  ),
  METRICS_DEFAULT_INTERVAL_MS: getEnv('METRICS_DEFAULT_INTERVAL_MS', '10000'),

  REDIS_URL: getEnv('REDIS_URL', 'redis://localhost:6379'),
  UPSTASH_REDIS_URL: getEnv('UPSTASH_REDIS_URL'),

  AUTH0_DOMAIN: getEnv('AUTH0_DOMAIN'),
  AUTH0_CLIENT_ID: getEnv('AUTH0_CLIENT_ID'),
  AUTH0_CLIENT_SECRET: getEnv('AUTH0_CLIENT_SECRET'),
  AUTH0_CALLBACK_URL: getEnv('AUTH0_CALLBACK_URL'),

  EXCHANGE_RATE_PRIMARY_API_URL: getEnv(
    'EXCHANGE_RATE_PRIMARY_API_URL',
    'https://api.exchangerate-api.com/v4/latest'
  ),
  EXCHANGE_RATE_FALLBACK_API_URL: getEnv('EXCHANGE_RATE_FALLBACK_API_URL', ''),
  RECEIPT_SCAN_CACHE_TTL_SECONDS: getEnv(
    'RECEIPT_SCAN_CACHE_TTL_SECONDS',
    '86400'
  ),
  RECEIPT_QUEUE_INTAKE_ENABLED: getEnv('RECEIPT_QUEUE_INTAKE_ENABLED', 'true'),
  RECEIPT_WORKER_ENABLED: getEnv('RECEIPT_WORKER_ENABLED', 'true'),
  RECEIPT_WORKER_CONCURRENCY: getEnv('RECEIPT_WORKER_CONCURRENCY', '2'),
  RECEIPT_MAX_ATTEMPTS: getEnv('RECEIPT_MAX_ATTEMPTS', '3'),
  RECEIPT_BACKOFF_DELAY_MS: getEnv('RECEIPT_BACKOFF_DELAY_MS', '10000'),
  RECEIPT_AI_RATE_LIMIT_MAX: getEnv('RECEIPT_AI_RATE_LIMIT_MAX', '10'),
  RECEIPT_AI_RATE_LIMIT_DURATION_MS: getEnv(
    'RECEIPT_AI_RATE_LIMIT_DURATION_MS',
    '60000'
  ),
  RECEIPT_DOWNLOAD_TIMEOUT_MS: getEnv('RECEIPT_DOWNLOAD_TIMEOUT_MS', '10000'),
  RECEIPT_PROCESSING_TIMEOUT_MS: getEnv(
    'RECEIPT_PROCESSING_TIMEOUT_MS',
    '60000'
  ),
  RECEIPT_MAX_DOWNLOAD_BYTES: getEnv(
    'RECEIPT_MAX_DOWNLOAD_BYTES',
    String(5 * 1024 * 1024)
  ),

  FRONTEND_ORIGIN: getEnv('FRONTEND_ORIGIN', 'localhost')
})

export const Env = envConfig()
